### ISSUE TITLE
Assignment 1

### ISSUE THREAD

**Issue by mgvirga** [angular-react-learning/node-learning#2]
Did not have enough time to get to server endpoints. Tried in my fs_example.js to compare values to see if they exist. Was unable to get working and need help.
[assignment1n.zip](https://github.com/angular-react-learning/node-learning/files/4458725/assignment1n.zip)

**Comment by mgvirga** [comment]
Got the endpoints to work but still having same issue with comparing values
[assignment1.zip](https://github.com/angular-react-learning/node-learning/files/4461551/assignment1.zip)

**Comment by angular-react-learning** [comment]
Looking into it.
